Vagrant.configure("2") do |config|
    # Erstelle die erste VM "database"
    config.vm.define "database" do |db|
      db.vm.box = "ubuntu/xenial64"
      db.vm.network "private_network", ip: "10.0.20.10"
      db.vm.hostname = "database"
      db.vm.provision "shell", inline: <<-SHELL
        # Installiere OpenSSH-Server
        sudo apt-get update
        sudo apt-get install -y openssh-server
        # Erstelle den Benutzer "luka" mit einem privaten SSH-Key
        sudo useradd -m -s /bin/bash luka
        sudo mkdir /home/luka/.ssh
        sudo cp /vagrant/ssh_keys/luka_key /home/luka/.ssh/id_rsa
        sudo cp /vagrant/ssh_keys/luka_key.pub /home/luka/.ssh/id_rsa.pub
        sudo chown -R luka:luka /home/luka/.ssh
        sudo chmod 700 /home/luka/.ssh
        sudo chmod 600 /home/luka/.ssh/*
      SHELL
    end
  
    # Erstelle die zweite VM "web"
    config.vm.define "web" do |web|
      web.vm.box = "ubuntu/xenial64"
      web.vm.network "private_network", ip: "10.0.20.11"
      web.vm.hostname = "web"
      web.vm.provision "shell", inline: <<-SHELL
        # Installiere OpenSSH-Server und MySQL-Client
        sudo apt-get update
        sudo apt-get install -y openssh-server mysql-client
        # Erstelle den Benutzer "luka" und füge seinen öffentlichen SSH-Key hinzu
        sudo useradd -m -s /bin/bash luka
        sudo mkdir /home/luka/.ssh
        sudo cp /vagrant/ssh_keys/luka_key.pub /home/luka/.ssh/authorized_keys
        sudo chown -R luka:luka /home/luka/.ssh
        sudo chmod 700 /home/luka/.ssh
        sudo chmod 600 /home/luka/.ssh/*
      SHELL
    end
  end
  