Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "vm1" do |vm1|
    vm1.vm.network "private_network", ip: "192.168.50.10"
    vm1.vm.network "forwarded_port", guest: 80, host: 8888
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.network "private_network", ip: "192.168.50.11"
    vm2.vm.network "forwarded_port", guest: 8888, host: 8080
    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.ssh.forward_agent = true
end
