Vagrant.configure("2") do |config|
    config.vm.define :reverseproxy do |reverseproxy|
        reverseproxy.vm.box = "ubuntu/xenial64"
        reverseproxy.vm.network :private_network, ip: "10.0.0.10"
        reverseproxy.vm.network "forwarded_port", guest:443, host:443, auto_correct: true
        reverseproxy.vm.network "forwarded_port", guest:80, host:80, auto_correct: true
        reverseproxy.vm.hostname = "reverseproxy"
        reverseproxy.vm.synced_folder "config/", "/etc/apache2/sites-enabled/"
        reverseproxy.vm.provision "shell", inline: <<-SHELL
        apt-get update
        sudo apt-get install apache2 -y
        sudo apt-get install ufw -y
        sudo apt-get install libapache2-mod-proxy-html -y
        sudo apt-get install libxml2-dev -y
        sudo apt-get install -y apache2
        sudo a2ensite 001-ssl.conf
        sudo a2enmod ssl
        sudo rm /etc/apache2/sites-enabled/000-default.conf
        sudo rm /etc/apache2/sites-enabled/default-ssl.conf
        sudo htpasswd -b -c /etc/apache2/.htpasswd vagrant Passwort
        sudo a2enmod proxy
        sudo a2enmod proxy_html
        sudo a2enmod proxy_http
        sudo ufw allow from 10.0.2.2 to any port 22
        sudo ufw allow 80/tcp
        sudo ufw allow 443/tcp
        sudo ufw --force enable
        SHELL
        reverseproxy.vm.provision "shell", path: "scripts/init.sh"
        reverseproxy.vm.provision "shell", inline: <<-SHELL
        sudo service apache2 restart
        SHELL
    end



    config.vm.define :web do |web|
        web.vm.box = "ubuntu/xenial64"
        web.vm.network :private_network, ip: "10.0.0.20"
        web.vm.hostname = "web"
        web.vm.synced_folder "html/", "/var/www/html"
        web.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get -y install apache2 ufw -y
        sudo ufw allow from 10.0.2.2 to any port 22
        sudo ufw allow from 10.0.0.10 to any port 80
        sudo ufw --force enable
        SHELL
    end
end